language: node_js

node_js: node

script: npm run build

deploy:
  provider: pages
  repo: vaicys.github.io
  target-branch: master
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
