name: Deploy
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repository: 'vaicys/vaicys.github.io'
      - shell: bash
        run: rm -f *
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git add --all
          git commit -m "Deploying build ${GITHUB_SHA::8}" || true
          git push
